
development:
  stations:
    - name: CAPE MAY CO
      state: NEW JERSEY
      lat: 39.008
      long: 74.908
      
    - name: ATLANTIC CITY
      state: NEW JERSEY
      lat: 39.35
      long: -74.433

    - name: SHIP JOHN SHOAL
      state: NEW JERSEY
      lat: 39.3
      long: -75.367

    - name: JACQUES COUSTEAU RES
      state: NEW JERSEY
      lat: 39.533
      long: -74.45

    - name: CHARLOTTESVILLE ALB
      state: VIRGINIA
      lat: 38.139
      long: -78.453

    - name: WINCHESTER RGNL
      state: VIRGINIA
      lat: 39.143
      long: -78.144

    - name: HAGERSTOWN RGNL RIC
      state: MARYLAND
      lat: 39.708
      long: -77.73

    - name: GRANT CO
      state: WEST VIRGINIA
      lat: 38.994
      long: -79.144
